import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"], // Specify subsets as needed
  weight: ['400', '700'], // Specify font weights as needed.  This example includes regular and bold.
  variable: "--font-montserrat", // This is optional, but helpful for CSS variables
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`} // Use Montserrat variable
      >
        {children}
      </body>
    </html>
  );
}
