export const products = [
    {
      id: 1,
      name: "Handmade Ceramic Mug",
      price: 15.99,
      description: "A beautiful handmade ceramic mug, perfect for your morning coffee.",
      longDescription: "Start your day with a touch of artisanal elegance. This handmade ceramic mug is thoughtfully crafted for those who appreciate the finer details. Its smooth finish, unique glaze, and comfortable handle make it perfect for your morning coffee or afternoon tea. Whether you’re savoring a hot cappuccino or herbal tea, this mug will quickly become your favorite companion.",
      image: "/products/handmade-ceramic-mug.jpg",
      rating: 4.5,
      category: "Kitchenware",
    },
    {
      id: 2,
      name: "Knitted Wool Scarf",
      price: 29.99,
      description: "A warm and cozy scarf, hand-knitted with premium wool.",
      longDescription: "Wrap yourself in warmth and style with this hand-knitted wool scarf. Made from high-quality, soft wool, it’s the perfect accessory for chilly days. The classic design pairs effortlessly with any outfit, adding both comfort and sophistication to your look. Whether you’re strolling through the city or hiking in the countryside, this scarf keeps you cozy.",
      image: "/products/knitted-wool-scarf.jpg",
      rating: 5.0,
      category: "Accessories",
    },
    {
      id: 3,
      name: "Wooden Cutting Board",
      price: 39.99,
      description: "A sturdy and elegant cutting board made from sustainable wood.",
      longDescription: "Upgrade your kitchen with this premium wooden cutting board, crafted from sustainable hardwood. Its sturdy design ensures durability, while the smooth surface is gentle on your knives. Perfect for preparing meals or serving cheeses and charcuterie, this cutting board is as functional as it is beautiful, making it a must-have for any home chef.",
      image: "/products/wooden-cutting-board.jpg",
      rating: 4.0,
      category: "Kitchenware",
    },
    {
      id: 4,
      name: "Handwoven Basket",
      price: 24.99,
      description: "A stylish and functional basket, perfect for storage or decor.",
      longDescription: "This handwoven basket is a versatile addition to your home decor. Use it for stylish storage or as a decorative accent piece. Each basket is carefully woven from natural fibers, giving it a rustic yet refined look. Ideal for holding blankets, toys, or magazines, it’s both practical and beautiful.",
      image: "/products/handwoven-basket.jpg",
      rating: 4.7,
      category: "Home Decor",
    },
    {
      id: 5,
      name: "Leather Journal",
      price: 19.99,
      description: "A handcrafted leather journal for your thoughts and sketches.",
      longDescription: "Capture your thoughts, sketches, and dreams in this handcrafted leather journal. The soft, genuine leather cover ages beautifully over time, making it a timeless keepsake. With its high-quality, lined paper, this journal is perfect for writers, artists, or anyone looking to stay organized in style.",
      image: "/products/leather-journal.jpg",
      rating: 4.8,
      category: "Stationery",
    },
    {
      id: 6,
      name: "Hand-Painted Vase",
      price: 34.99,
      description: "A unique vase featuring hand-painted floral designs.",
      longDescription: "Add a touch of artistry to your home with this hand-painted vase. Featuring intricate floral designs, it’s a stunning centerpiece for any room. Whether you fill it with fresh blooms or leave it as a standalone decor piece, this vase brings charm and elegance to your space.",
      image: "/products/hand-painted-vase.jpg",
      rating: 4.6,
      category: "Home Decor",
    },
    {
      id: 7,
      name: "Crochet Blanket",
      price: 49.99,
      description: "A soft and cozy crochet blanket, perfect for chilly evenings.",
      longDescription: "Cozy up with this beautifully crafted crochet blanket, perfect for chilly evenings or lazy weekends. Made from soft yarn, it offers warmth without sacrificing style. Drape it over your sofa or bed to add texture and warmth to your living space.",
      image: "/products/crochet-blanket.jpeg",
      rating: 4.9,
      category: "Home Decor",
    },
    {
      id: 8,
      name: "Handmade Soap Set",
      price: 12.99,
      description: "A set of natural handmade soaps with soothing scents.",
      longDescription: "Indulge in the soothing scents and natural ingredients of this handmade soap set. Each bar is crafted with care, using skin-friendly formulas that leave your skin feeling soft and refreshed. Perfect as a gift or a personal treat, these soaps turn your daily routine into a luxurious experience.",
      image: "/products/handmade-soap-set.jpg",
      rating: 4.3,
      category: "Personal Care",
    },
    {
      id: 9,
      name: "Macramé Wall Hanging",
      price: 27.99,
      description: "A bohemian-style macramé wall hanging for home decor.",
      longDescription: "Bring bohemian vibes to your home with this macramé wall hanging. Each piece is intricately knotted by hand, creating a beautiful blend of texture and design. Hang it in your living room, bedroom, or office for an instant style upgrade.",
      image: "/products/macrame-wall-hanging.jpg",
      rating: 4.7,
      category: "Home Decor",
    },
    {
      id: 10,
      name: "Handcrafted Candle",
      price: 9.99,
      description: "A hand-poured soy candle with a relaxing lavender scent.",
      longDescription: "Relax and unwind with this hand-poured soy candle, infused with a calming lavender scent. The clean-burning wax and minimalist design make it a perfect addition to any room. Light it during your evening routine to create a serene, spa-like atmosphere.",
      image: "/products/handcrafted-candle.jpg",
      rating: 4.4,
      category: "Home Decor",
    },
    {
      id: 11,
      name: "Embroidered Pillow Cover",
      price: 18.99,
      description: "A beautiful decorative pillow cover with intricate embroidery.",
      longDescription: "Elevate your living space with this beautifully embroidered pillow cover. Featuring detailed patterns and vibrant colors, it’s a perfect accent for your sofa or bed. The high-quality fabric ensures durability and comfort, making it both stylish and functional.",
      image: "/products/embroidered-pillow-cover.jpg",
      rating: 4.6,
      category: "Home Decor",
    },
    {
      id: 12,
      name: "Handmade Pottery Bowl",
      price: 22.99,
      description: "A beautifully crafted pottery bowl, perfect for serving or display.",
      longDesciption: "This handmade pottery bowl combines rustic charm with modern functionality. Its smooth glaze and organic shape make it ideal for serving salads, fruits, or snacks. Whether used daily or as a decorative piece, this bowl is a testament to artisanal craftsmanship.",
      image: "/products/handmade-pottery-bowl.jpg",
      rating: 4.5,
      category: "Kitchenware",
    },
    {
      id: 13,
      name: "Hand-Stitched Tote Bag",
      price: 14.99,
      description: "A durable and stylish tote bag, hand-stitched with care.",
      longDescription: "Carry your essentials in style with this hand-stitched tote bag. Designed for durability and everyday use, it’s perfect for trips to the market or casual outings. The minimalist design and sturdy construction make it a must-have accessory.",
      image: "/products/hand-stitched-tote-bag.jpg",
      rating: 4.2,
      category: "Accessories",
    },
    {
      id: 14,
      name: "Handmade Dreamcatcher",
      price: 19.99,
      description: "A decorative dreamcatcher with feathers and beads.",
      longDescription: "Add a touch of magic to your space with this handmade dreamcatcher. Featuring delicate feathers and beads, it’s a beautiful symbol of protection and positivity. Hang it above your bed or in a special spot to inspire sweet dreams and good energy.",
      image: "/products/handmade-dreamcatcher.jpg",
      rating: 4.1,
      category: "Home Decor",
    },
    {
      id: 15,
      name: "Hand-Painted Coasters",
      price: 8.99,
      description: "A set of coasters featuring unique hand-painted designs.",
      longDescription: "Protect your surfaces in style with this set of hand-painted coasters. Each coaster features a unique design, adding a pop of color and personality to your table. Perfect for entertaining guests or as a thoughtful gift.",
      image: "/products/hand-painted-coasters.jpg",
      rating: 4.0,
      category: "Kitchenware",
    },
    {
      id: 16,
      name: "Handwoven Table Runner",
      price: 29.99,
      description: "A elegant table runner, handwoven with natural fibers.",
      longDescription: "Transform your dining table with this elegant handwoven table runner. Made from natural fibers, it adds texture and warmth to any setting. Whether you’re hosting a dinner party or enjoying a casual meal, this runner brings a touch of rustic charm.",
      image: "/products/handwoven-table-runner.jpg",
      rating: 4.7,
      category: "Home Decor",
    },
    {
      id: 17,
      name: "Handmade Jewelry Box",
      price: 45.99,
      description: "A beautifully crafted wooden jewelry box with intricate details.",
      longDescription: "Keep your precious items safe and organized with this handcrafted wooden jewelry box. Featuring intricate details and a smooth finish, it’s both functional and decorative. Perfect for storing rings, necklaces, or keepsakes, it’s a beautiful addition to any dresser or vanity.",
      image: "/products/handmade-jewelry-box.jpg",
      rating: 4.9,
      category: "Accessories",
    },
  ];