export const products = [
    {
      id: 1,
      name: "Handmade Ceramic Mug",
      price: 15.99,
      description: "A beautiful handmade ceramic mug, perfect for your morning coffee.",
      image: "/products/handmade-ceramic-mug.jpg",
      rating: 4.5,
      category: "Kitchenware",
    },
    {
      id: 2,
      name: "Knitted Wool Scarf",
      price: 29.99,
      description: "A warm and cozy scarf, hand-knitted with premium wool.",
      image: "/products/knitted-wool-scarf.jpg",
      rating: 5.0,
      category: "Accessories",
    },
    {
      id: 3,
      name: "Wooden Cutting Board",
      price: 39.99,
      description: "A sturdy and elegant cutting board made from sustainable wood.",
      image: "/products/wooden-cutting-board.jpg",
      rating: 4.0,
      category: "Kitchenware",
    },
    {
      id: 4,
      name: "Handwoven Basket",
      price: 24.99,
      description: "A stylish and functional basket, perfect for storage or decor.",
      image: "/products/handwoven-basket.jpg",
      rating: 4.7,
      category: "Home Decor",
    },
    {
      id: 5,
      name: "Leather Journal",
      price: 19.99,
      description: "A handcrafted leather journal for your thoughts and sketches.",
      image: "/products/leather-journal.jpg",
      rating: 4.8,
      category: "Stationery",
    },
    {
      id: 6,
      name: "Hand-Painted Vase",
      price: 34.99,
      description: "A unique vase featuring hand-painted floral designs.",
      image: "/products/hand-painted-vase.jpg",
      rating: 4.6,
      category: "Home Decor",
    },
    {
      id: 7,
      name: "Crochet Blanket",
      price: 49.99,
      description: "A soft and cozy crochet blanket, perfect for chilly evenings.",
      image: "/products/crochet-blanket.jpeg",
      rating: 4.9,
      category: "Home Decor",
    },
    {
      id: 8,
      name: "Handmade Soap Set",
      price: 12.99,
      description: "A set of natural handmade soaps with soothing scents.",
      image: "/products/handmade-soap-set.jpg",
      rating: 4.3,
      category: "Personal Care",
    },
    {
      id: 9,
      name: "Macramé Wall Hanging",
      price: 27.99,
      description: "A bohemian-style macramé wall hanging for home decor.",
      image: "/products/macrame-wall-hanging.jpg",
      rating: 4.7,
      category: "Home Decor",
    },
    {
      id: 10,
      name: "Handcrafted Candle",
      price: 9.99,
      description: "A hand-poured soy candle with a relaxing lavender scent.",
      image: "/products/handcrafted-candle.jpg",
      rating: 4.4,
      category: "Home Decor",
    },
    {
      id: 11,
      name: "Embroidered Pillow Cover",
      price: 18.99,
      description: "A beautiful decorative pillow cover with intricate embroidery.",
      image: "/products/embroidered-pillow-cover.jpg",
      rating: 4.6,
      category: "Home Decor",
    },
    {
      id: 12,
      name: "Handmade Pottery Bowl",
      price: 22.99,
      description: "A beautifully crafted pottery bowl, perfect for serving or display.",
      image: "/products/handmade-pottery-bowl.jpg",
      rating: 4.5,
      category: "Kitchenware",
    },
    {
      id: 13,
      name: "Hand-Stitched Tote Bag",
      price: 14.99,
      description: "A durable and stylish tote bag, hand-stitched with care.",
      image: "/products/hand-stitched-tote-bag.jpg",
      rating: 4.2,
      category: "Accessories",
    },
    {
      id: 14,
      name: "Handmade Dreamcatcher",
      price: 19.99,
      description: "A decorative dreamcatcher with feathers and beads.",
      image: "/products/handmade-dreamcatcher.jpg",
      rating: 4.1,
      category: "Home Decor",
    },
    {
      id: 15,
      name: "Hand-Painted Coasters",
      price: 8.99,
      description: "A set of coasters featuring unique hand-painted designs.",
      image: "/products/hand-painted-coasters.jpg",
      rating: 4.0,
      category: "Kitchenware",
    },
    {
      id: 16,
      name: "Handwoven Table Runner",
      price: 29.99,
      description: "A elegant table runner, handwoven with natural fibers.",
      image: "/products/handwoven-table-runner.jpg",
      rating: 4.7,
      category: "Home Decor",
    },
    {
      id: 17,
      name: "Handmade Jewelry Box",
      price: 45.99,
      description: "A beautifully crafted wooden jewelry box with intricate details.",
      image: "/products/handmade-jewelry-box.jpg",
      rating: 4.9,
      category: "Accessories",
    },
  ];